<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>vla_kinova_teleop</name>
  <version>0.0.0</version>
  <description>Twist-based teleoperation for the Kinova Gen3 (Quest 3 EE pose tracking via the Kortex twist controller).</description>
  <maintainer email="filippogorini7@gmail.com">filippo</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>vla_kinova_bringup</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>picknik_twist_controller</exec_depend>
  <exec_depend>python3-transforms3d</exec_depend>
  <exec_depend>ros_tcp_endpoint</exec_depend>
  <exec_depend>q2r2_bringup</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
